### ISSUE TITLE
Creating order is very slow

### ISSUE THREAD

**Issue by PeterNaaijen** [janssenr/RaboOmniKassaApi.Net#1]
Thank you for your code, we have also some customers with Rabo Omnikassa so we recently changed ROK1.0 to 2.0
This piece of code takes several seconds which is too slow in my opinion:
![image](https://user-images.githubusercontent.com/46248697/50541383-0a30f200-0ba5-11e9-99d3-d84fd3b9e8d8.png)

Is there something you can do about it?

**Comment by janssenr** [comment]
I don't think I can do someting about it.
Because it's the call to the Rabobank OmniKassa server which takes long:
```            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _token);
            var content = new StringContent(body, Encoding.UTF8, "application/json");
            var response = _client.PostAsync(path, content).Result;
            if (response.IsSuccessStatusCode)
                return response.Content.ReadAsStringAsync().Result;
            HandleResponseError(response);
            return null;
```
This line takes long:
```
            var response = _client.PostAsync(path, content).Result;
```
And that's the call to the Rabobank OmniKassa server.

**Comment by PeterNaaijen** [comment]
So we should report/ask it to the Rabobank?

Op zo 30 dec. 2018 10:35 schreef Rob Janssen <notifications@github.com:

**Comment by janssenr** [comment]
I will report/ask it.

**Comment by janssenr** [comment]
Received a response from the Rabobank:
Problem is due ‘Expect: 100-continue’ header which is sent by default with every POST request in .NET
This header is not (correctly) supported by OmniKassa at the moment.
Rabobank is busy solving this issue, but for the time being, a (temporary) solution is:
_client.DefaultRequestHeaders.ExpectContinue = false

Changed the code and now creating the order is much faster!

**Comment by PeterNaaijen** [comment]
Thank you very much, we will also change code and try!
