### ISSUE TITLE
Invalid or missing signature

### ISSUE THREAD

**Issue by joshi-priyanka** [janssenr/RaboOmniKassaApi.Net#2]
When I make the call "EndPoint.AnnounceMerchantOrder', then I receive ""invalid or missing signature" every time. 

For the MerchantOrder.Signature, I provide the "signingKey" as a parameter. Where am I going wrong?

**Comment by janssenr** [comment]
You should not set MerchantOrder.Signature! The signature is calculated!
The "SigningKey" is passed as a parameter to the EndPoint constructor.

Don't you use the example code I provided?

**Comment by joshi-priyanka** [comment]
When I did not set MerchantOrder.Signature, I still got the same error. However, the issue is resolved now. The problem was with the encoding of Signing Key. 

It works fine now. Thanks for the prompt response.
